### ISSUE TITLE
Can't add new board

### ISSUE THREAD

**Issue by AD1337** [nathanhoad/godot_puzzle_dependencies#1]
**Describe the bug**
Can't add a new board. I get  I'm still on Godot 3.4.4, could this be the problem?

**Error log**
*On plugin loaded*
SCRIPT ERROR: Parse Error: The method "merge" isn't declared on base "Dictionary".
          at: GDScript::reload (res://addons/puzzle_dependencies/views/edit_board_dialog.gd:30)
ERROR: Method failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:577)

*On clicked 'Add a new board' button*
SCRIPT ERROR: Invalid call. Nonexistent function 'edit_board' in base 'ConfirmationDialog (edit_board_dialog.gd)'.
          at: _on_AddBoardButton_pressed (res://addons/puzzle_dependencies/views/main_view.gd:182)

**Comment by delleloper** [comment]
It happens the same to me!

**Comment by nathanhoad** [comment]
I forgot that `.merge` was only added to dictionaries in 3.5. I've replaced the merge calls with manual key setters.

**Comment by AD1337** [comment]
Works great now, thanks! Maybe I should just update to 3.5 already.
Oh wait, I found another bug... I'll open a new report.
Nevermind. It was that I was unable to create boards after the first one, or rename the first one, but restarting fixed it. The error was:
`res://addons/puzzle_dependencies/views/edit_board_dialog.gd:18 - Invalid set index 'text' (on base: 'Nil') with value of type 'String`
I can't reproduce it.
